### ISSUE TITLE
install error on UBUNTU 18.04--python3.6

### ISSUE THREAD

**Issue by myrainbowandsky** [taishi-i/nagisa#20]
home/wentao/programming/weibospider/config/conf.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cf = load(cont)
[dynet] random seed: 1234
[dynet] allocating memory: 32MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "multi_token.py", line 12, in <module>
    import  nagisa
  File "/home/wentao/programming/tweet/py3_all/lib/python3.6/site-packages/nagisa/__init__.py", line 3, in <module>
    from nagisa.train import fit
  File "/home/wentao/programming/tweet/py3_all/lib/python3.6/site-packages/nagisa/train.py", line 12, in <module>
    import prepro
  File "/home/wentao/programming/tweet/py3_all/lib/python3.6/site-packages/nagisa/prepro.py", line 11, in <module>
    OOV = utils.OOV
AttributeError: module 'utils' has no attribute 'OOV'

my working dir has no utils.py

**Comment by taishi-i** [comment]
Hi, @myrainbowandsky 
Thank you for using nagisa.

Did you solve this issue?
If you have any questions, don't hesitate to contact me.

Thank you

**Comment by myrainbowandsky** [comment]
@taishi-i 
Yes. I fixed that. I was using virtualenv, then I have ' AttributeError: module 'utils' has no attribute 'OOV'' problem.
 I resintall Nagisa in a terminal and then launch virtualenv. that woks.
